import requests
import os
import pygit2
import namegenerator

version = 'v0.1.0-SNAPSHOT'
terminal_title = f"WS Datapack Development Environment Setup Helper {version}"
print(f'\33]0;{terminal_title}\a', end='', flush=True)

def pause():
    programPause = input("Press the <ENTER> key to continue...")

print(f"WS Datapack Development Environment Setup Helper {version}")
print("This will set up a development environment for the WS Datapack.")
print("If you want to make a documentation change, this will not make the needed changes for that and you should press Ctrl+C now.")
print("After that, download the latest docs script from https://raw.githubusercontent.com/osfanbuff63/ws-datapack/master/scripts/setup/docs.py if using Unix or Windows, or the latest .exe from Actions if using Windows.")
print("You can copy that link into a browser, `wget`, `curl`, I don't care lol.")
pause()

repo_url = 'git://github.com/osfanbuff63/ws-datapack'
repo_path = '~/ws-datapack'
repo = pygit2.clone_repository(repo_url, repo_path)
branch_name = f'autogenerated/{namegenerator.gen()}'

